spring: 
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java 
      exclude: WEB_INF/**   
  application:
    name: msa-weather-collection-eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/